# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=32)),
                ('issue_desc', models.CharField(max_length=1024)),
                ('issue_completed', models.IntegerField(default=0)),
                ('issue_startdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=32)),
                ('lab_desc', models.CharField(max_length=512)),
                ('lab_color', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=32)),
                ('proj_desc', models.CharField(max_length=1024)),
                ('proj_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('proj_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='git_project.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='git_project.Project'),
        ),
    ]
