# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=64)),
                ('proj_desc', models.CharField(max_length=256)),
                ('proj_opened', models.BooleanField()),
                ('proj_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
