# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='git_project.Label'),
        ),
    ]
