# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0002_project_projecthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=64)),
                ('issue_desc', models.CharField(max_length=256)),
                ('issue_opened', models.BooleanField()),
                ('issue_completed', models.IntegerField(default=0)),
                ('issue_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('proj_id_issue', models.IntegerField()),
                ('label_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=32)),
                ('lab_desc', models.CharField(max_length=128)),
                ('lab_color', models.CharField(max_length=32)),
            ],
        ),
    ]
