# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0011_auto_20170208_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
