# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0014_auto_20170222_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
