# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0018_auto_20170226_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
