# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0019_auto_20170226_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
