# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0025_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proj_start',
        ),
    ]
