# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0031_auto_20170306_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=32)),
                ('branch_desc', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commit',
            name='commit_link',
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_body',
            field=models.CharField(default='', max_length=16384),
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='git_project.Project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='git_project.Branch'),
        ),
    ]
