# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0034_commit_commit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='commit_date',
        ),
    ]
