# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0035_remove_commit_commit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_body',
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_title',
            field=models.CharField(max_length=64),
        ),
    ]
