# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_project', '0036_auto_20170313_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='issue_change',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoryItem',
        ),
        migrations.DeleteModel(
            name='IssueChange',
        ),
        migrations.DeleteModel(
            name='ProjectHistory',
        ),
    ]
